Module 12
permidon/qna pull request #10
Opened 2017-03-17 02:24 UTC by permidon

Аутентификация через Facebook и Twitter. Реализованы случаи, когда провайдер возвращает и не возвращает email. Для второго случая добавлена возможность залогиниться через провайдера только после подтверждения электронного адреса.

2017-03-17 02:26 UTC, permidon commented on app/controllers/omniauth_callbacks_controller.rb
> +
Устраню лишний пробел при следующем коммите

2017-03-17 08:32 UTC, vkurennov requested changes
В целом хорошо, но для хранения данных от провайдера используй сессию. И не забудь ее очищать после успешного логина

2017-03-17 08:32 UTC, vkurennov commented on app/views/devise/registrations/confirm_email.html.slim
> +    = hidden_field_tag 'auth[unconfirm]', 'true'
Вот это не очень хорошо - светить данные (скрытые поля легко посмотреть), лучше их хранить в сессии, она шифруется.

2017-03-19 10:48 UTC, vkurennov approved these changes

2017-03-19 10:48 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +      session[:provider_data] = nil
Чтобы не очищать сессию вручную, есть небольшой лайфхак: достаточно ключ сессии сдлеать строкой и начать с `devise.`, например, `'devise.provider_data'`, тогда после успешного логина девайс автоматом очистит такие значения в сессии.

2017-03-19 16:35 UTC, merged