Module 5
permidon/qna pull request #3
Opened 2017-02-14 03:07 UTC by permidon

Реализованы истории, начиная с acceptance-тестов: создание вопроса и ответа на странице вопроса, просмотр списка вопросов, просмотр вопроса и ответов к нему, аутентификация. Только аутентифицированный пользователь может создавать вопросы и ответы, только автор может удалять свои вопросы и свои ответы.

2017-02-14 09:55 UTC, vkurennov requested changes

2017-02-14 09:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user == @answer.user
Здесь ты грузишь ассоциацию user у ответа, но ведь она нам не нужна, нам нужно только проверить на автора, а для этого достаточно проверить по user_id не загружая сам объект из базы. 
И такая проверка еще не раз понадобится, поэтому вынеси ее в метод `User#author_of?`

2017-02-14 09:55 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @answer.question
Можно совместить редирект и флеш-сообщение: `redirect_to @answer.question, notice: "...."`

2017-02-14 09:55 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.destroy if current_user == @question.user
Сравнивай по id и примени метод `User#author_of?`

2017-02-14 09:55 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:title, :body, :user_id)
user_id не приходит в параметрах формы, мы берем его из current_user,  так что здесь это лишнее

2017-02-14 09:55 UTC, vkurennov commented on app/views/questions/new.html.slim
> +          = form_for @question do |f|
Тут еще ошибки валидации надо выводить

2017-02-14 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @question.user == current_user
Сравнивай по id и примени метод `User#author_of?`

2017-02-14 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      p = link_to 'Delete question', question_path(@question), method: :delete, class: 'btn btn-danger btn-sm'
Вторым параметром можно просто `@question` передавать, это то же самое, что и `question_path(@question)`

2017-02-14 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +            - if answer.user == current_user
Сравнивай по id и примени метод `User#author_of?`

2017-02-14 09:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers/form'
А почему этого файла нет в PR? Убедись, что там есть вывод ошибок валидации

2017-02-14 09:55 UTC, vkurennov commented on db/migrate/20170211004629_add_user_id_to_questions_and_answers.rb
> +    add_belongs_to :answers, :user
Добавляй еще опцию` foreign_key: true`, чтобы на уровне базы следить за целостностью данных

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content 'The answer has been successfully created.'
Надо проверить, что на странице появился текст ответа

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
нужен сценарий на невалидный овтет. Все ошибки валидации проверять не нужно (это мы делаем в модели), но надо проверить, что система выводит юзеру хотя бы одну ошибку валидации

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'The question has been successfully created.'
Нужно проверить, что заголовок и текст вопроса появились на странице

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Также нужен сценарий на невалидный вопрос, т.е. то, что ситема сообщает юзеру об ошибках валидации

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_content 'The answer has been successfully deleted.'
Нужно проверить, что ответа больше нет на странице

2017-02-14 09:55 UTC, vkurennov commented on spec/acceptance/delete_question_spec.rb
> +    expect(page).to have_content 'The question has been successfully deleted.'
Нужно проверить, что вопроса больше нет на странице со списком вопросов

2017-02-14 09:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      context 'with valid attributes' do
Тут нужно еще проверить, что ответ свзяывается с залогиненным юзером

2017-02-14 09:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      context 'with invalid attributes' do
А зачем 2 контекста? Достаточно просто проверить, что незалогиненный юзер перенаправляется на страницу логина, ведь в этом случае до экшена дело не доходит и валидация не выполняется. Так что тут просто дублирование тестов

2017-02-14 09:55 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      context 'with valid attributes' do
Опять же не нужны здесь 2 контекста

2017-02-14 14:34 UTC, permidon commented on app/views/questions/show.html.slim
> +  = render 'answers/form'
Вот странно, что он в PR не попал, хотя вот в последнем коммите он есть - https://github.com/permidon/qna/tree/module_5/app/views/answers 
И сделал я его после прошлого PR. Вывод ошибок валидации в него внес, но хочу, чтобы ошибки показывало прямо на странице вопроса, а не перенаправляло на отдельную страницу ответа. Пока не придумал как реализовать

2017-02-14 15:41 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render 'answers/form'
Желание верное, нужно просто вывести у формы ошибки валидации через паршл и  в контроллере рендерить в случае ошибки вид questions/show

2017-02-14 15:57 UTC, vkurennov requested changes

2017-02-14 15:57 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Вот здесь нужно рендерить страницу вопроса, а экшн new вообще не нужен

2017-02-14 15:57 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
Экшн new лишний

2017-02-14 15:57 UTC, vkurennov commented on app/views/answers/new.html.slim
> += render 'form'
Опять же, new не нужен

2017-02-14 15:57 UTC, vkurennov commented on app/views/answers/show.html.slim
> +p = @answer.body
И show не нужен, у тебя все ответы на странице вопроса. Можно использовать анонимные паршалы, они позже еще пригодятся. Но тогда в них и ссылки на удаление должны быть

2017-02-14 15:57 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +    expect(page).to have_no_content 'Delete answer'
тут лучше использовать have_link (have_no_link)

2017-02-14 15:57 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          expect(assigns(:answer).user).to eq @user
В unit-тестах принято правило: один тест - один expect, так что это должно быть 2 разных теста

2017-02-14 17:42 UTC, permidon commented on app/controllers/answers_controller.rb
>        render :new
Если я делаю рендер на 'questions/show', то у он у меня сыпется на строке
`= link_to 'Delete answer', answer_path(answer), method: :delete, class: 'btn btn-danger btn-xs'`
с ошибкой
`No route matches {:action=>"show", :controller=>"answers", :id=>nil} missing required keys: [:id]`

2017-02-15 09:24 UTC, vkurennov requested changes

2017-02-15 09:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @answer.question, notice: 'The answer has been successfully deleted.'
А если проверка не прошла, сообщение тоже будет об успешном удалении? Как-то не логично.

2017-02-15 09:24 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path, notice: 'The question has been successfully deleted.'
Если это не автор, то сообщение не релевантно

2017-02-15 09:24 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А где же тесты на метод `author_of?`. Прежде чем писать какой-либо код, остановись и убедись, что есть тесты на него. Если их нет, начни с тестов. Спроси себя "как этот метод должен работать" и начни с первого ответа и первого теста и постепенено добавляй тесты на различные условия, меняя код так, чтобы тесты начали проходить.

2017-02-15 14:39 UTC, permidon commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
PR перекосило чтоль? Добавил тесты, но тут их почему-то не видно. Вот:
https://github.com/permidon/qna/pull/3/commits/8b49c5544d4a4c617b6cbbcf8ca88ecfbb3371ad

2017-02-15 14:52 UTC, vkurennov approved these changes

2017-02-15 14:52 UTC, vkurennov commented on spec/models/user_spec.rb
> +        expect(author.author_of?(question)).to eq true
Есть в rspec клевая штука для методов-предикатов (на знак вопроса заканчиваются). Можно писать так: `expect(author).to be_author_of(question)`
То есть, ставим метод после to/to_not, добавляем be_ и убираем восклицательный знак.

2017-02-15 16:49 UTC, merged