Module 7
permidon/qna pull request #5
Opened 2017-02-21 02:28 UTC by permidon

Только автор может отредактировать свой вопрос или ответ. Удаление ответов через AJAX.
Автор вопроса может выбрать лучший ответ (только 1). Автор вопроса может выбрать другой лучший ответ. Если у вопроса есть лучший ответ, то он отображается первым в списке ответов, остальные по дате создания, если лучшего ответа нет, то просто по дате создания.

После редактирования ответа рендерю весь список ответов. Или нужно лишь перерисовывать редактируемый ответ?
Тоже самое с пометкой лучшего ответа, но тут их нужно пересортировывать каждый раз.
Не понимаю, как так вышло, но повторная попытка пометить ответ как лучший делает его обычным (такой задумки не было). Пока оставил так, но там явно где-то ошибка.

2017-02-21 08:53 UTC, vkurennov requested changes

2017-02-21 08:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.reset_best_status
Это все бизнес-логика (логика, меняющая состояние системы), ей не место в контроллере. Вынеси ее в метод модели, а здесь просто вызывай этот метод

2017-02-21 08:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @question.reset_best_status
И это все относится в ответу, а не к вопросу, так что лучше метод поместить в модель Answer

2017-02-21 08:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      @answer.update(best: true)
Т.к. тут может быть несколько изменений, то когда все это вынесешь в метод, оберни в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2017-02-21 08:53 UTC, vkurennov commented on app/models/answer.rb
> +  scope :helpful, -> { order(best: :desc).order(created_at: :asc) }
Простые скоупы (как этот) можно не тестировать, более сложные, лучше тестировать. Тесты пишутся просто: создаем несколько объектов, одни подпадают под скоуп, другие нет, пишем тесты, которые проверяют, что нужные объекты возвращаются скоупом, а не подходящие - не возвращаются

2017-02-21 08:53 UTC, vkurennov commented on app/models/question.rb
> +    self.answers.each do |answer|
Есть метод update_all для таких вещей. И лучше все это объеденить в один метод (вместе с установкой лучшего ответа) и обернуть в транзакцию

2017-02-21 08:53 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if answer.best == true
Никогда не сравнивай с true/false/nil. Это выглядит громоздко и очень непрофессионально. У тебя атрибут answer.best и так возвращает true/false, так какой смысл писать `if true == true` или `if true == false`, если достаточно просто `if true` или `if false`?

А чтобы совсем было красиво, используй метод-предикат `best?`, их рельсы создают автоматом для булевых атрибутов

2017-02-21 08:53 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      - if answer.best
Ну вот, здесь же без сравнвания с true написал

2017-02-21 08:53 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +$('.answers').html('<%= j render @question.answers.helpful %>');
Тут нужно удалять только удаленный ответ со страницы

2017-02-21 08:53 UTC, vkurennov commented on app/views/answers/mark_best.js.erb
> +$('.answers').html('<%= j render @question.answers.helpful %>');
Здесь можно рендерить весь список, иначе, слишком сложный js надо писать

2017-02-21 08:53 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @question.answers.helpful %>');
Надо обновлять только измененный ответ, без рендеринга всего списка

2017-02-21 08:53 UTC, vkurennov commented on app/views/questions/update.js.erb
> +$('.edit-question-errors-form').html('');
Отступы не забывай, иначе код читать невозможно

2017-02-21 08:53 UTC, vkurennov commented on app/views/questions/update.js.erb
> +$('.question').html('<%= j render @question %>');
Обновляем только измененный ответ

2017-02-21 08:53 UTC, vkurennov commented on spec/acceptance/delete_answer_spec.rb
> +  scenario 'Authenticated user deletes other answer', js: true do
Здесь, кстати, `js: true` не нужен, т.к. запроса-то не происходит, а проверить, что нет ссылки мы можем и без js

2017-02-21 08:53 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +  scenario 'Non-authenticated user edits an answer', js: true do
тут можно обойтись без `js:true`

2017-02-21 08:53 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          expect(answer.best).to eq true
Можно писать `expect(answer).to be_best`.  это всроенная фишка rspec для любых методов-предикатов

2017-02-21 17:00 UTC, permidon commented on app/views/answers/_answer.html.slim
> +    - if answer.best == true
Тут у меня косяк с выводом пометки произошел, я начал искать в чем причина, менял все так и сяк, и забыл вернуть к хорошему виду ) Буду внимательней

2017-02-21 18:17 UTC, permidon commented on app/views/questions/update.js.erb
> +$('.question').html('<%= j render @question %>');
Так и есть, часть с ответами не трогаю

2017-02-22 07:44 UTC, vkurennov commented on app/views/questions/update.js.erb
> +$('.question').html('<%= j render @question %>');
А, да, это же вопрос, точно

2017-02-22 07:51 UTC, vkurennov approved these changes
Принято, но поправь замечания перед выполнением следующего задания

2017-02-22 07:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body, :best)
А зачем тебе в параметрах best? Он же не приходит в форме

2017-02-22 07:51 UTC, vkurennov commented on app/models/answer.rb
> +      self.update(best: true)
Транзакция откатывается только в случае исключения, поэтому надо использовать метод `update!`,  чтобы в случае чего было исключение

2017-02-22 07:51 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +        li= link_to 'Remove the mark of best answer', mark_best_answer_path(answer), method: :patch, remote: true
Меняется только название, ссылка-то одна и та же, так что можно по условию просто название менять

2017-02-22 07:51 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +$("#unit-answer-<%= @answer.id %>").hide();
1. Длинноват id элемента, достаточно просто `answer-<id>`
2. Лучше remove использовать, зачем скрывать удаленный ответ, он же все равно уже удален.

2017-02-22 07:51 UTC, vkurennov commented on spec/acceptance/mark_best_answer.rb
> +  scenario 'Author marks the answers as the best', js: true do
Тут нужен еще сценарий, проверяющий, что лучший ответ - первый в списке

2017-02-22 07:51 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  context "set best_status" do
Методы описываются в describe, в вот внутри уже можно использовать context.

2017-02-22 16:32 UTC, merged